// AUTO-GENERATED by scripts/translate-i18n.mjs
// Do not edit manually. Run: node scripts/translate-i18n.mjs

import { ja } from "./ja";
import { ko } from "./ko";
import { zh_TW } from "./zh_TW";
import { vi } from "./vi";
import { es } from "./es";

export { ja, ko, zh_TW, vi, es };
